apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: write-catalog-info
  title: Writes the catalog-info file for a given Entity
  description: Writes the catalog-info file for a given Entity
  tags:
    - import
    - catalog
    - register
    - fetch
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Catalog Entity Details
      properties:
        entityReference: 
          title: Entity reference
          type: string
          description: Entity reference of the entity to get
          ui:field: EntityPicker
          ui:options:
             allowArbitraryValues: true

  steps:

  - id: fetch
    name: Fetch catalog entity
    action: catalog:fetch
    input:
      entityRef: ${{parameters.entityReference}}

  - id: create-catalog-info-file
    name: Create catalog file
    action: catalog:write
    input:
      entity: |
         ${{steps.fetch.output.entity}}
  
  - id: parse
    name: read file
    action: roadiehq:utils:fs:parse
    input:
      path: ./catalog-info.yaml
      parser: yaml

  - id: serialize
    name: Serialize
    action: roadiehq:utils:serialize:yaml
    input:
      data: ${{ steps['parse'].output.content }}

  - id: log
    name: Console.log
    action: debug:log
    input:
      message: |
        Content: `${{ steps['serialize'].output.serialized }}`



