apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: write-catalog-info
  title: Writes the catalog-info file for a given Entity
  description: Writes the catalog-info file for a given Entity
  tags:
    - import
    - catalog
    - register
    - fetch
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Catalog Entity Details
      properties:
        entityReq: 
          title: Entity
          type: string
          description: Entity to write the catalog-info.yaml file for
          ui:widget: textarea
          ui:options:
            rows: 10

  steps:
  - id: create-catalog-info-file
    name: Create catalog file
    action: catalog:write
    input:
      entity: |
         ${{parameters.entityReq}}
  
  - id: parse
    name: read file
    action: roadiehq:utils:fs:parse
    input:
      path: ./catalog-info.yaml
      parser: yaml

  - id: serialize
    name: Serialize
    action: roadiehq:utils:serialize:yaml
    input:
      data: ${{ steps['parse'].output.content }}

  - id: log
    name: Console.log
    action: debug:log
    input:
      message: |
        Content: `${{ steps['serialize'].output.serialized }}`



