apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Message Logger
  title: Writes a message into the log after waiting for a certain period of time
  description: Writes a message into the log after waiting for a certain period of time
  tags:
    - recommended
spec:
  owner: janus-authors
  system: janus-idp
  type: service
  parameters:
    - title: Log Message entry
      required:
        - logMsg
      properties:
        logMsg:
          title: Enter Log Message
          type: string
          description: Provide Message for logging

  steps:
    - id: log-info
      name: Log the wait time duration
      action: debug:log
      input:
        message: Waiting for ${{parameters.logMsg}} before logging message
