apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Message Logger
  title: Writes a message into the log after waiting for a certain period of time
  description: Writes a message into the log after waiting for a certain period of time
  tags:
    - recommended
spec:
  owner: janus-authors
  system: janus-idp
  type: service
  parameters:
    - title: Log Message entry
      required:
        - logMsg
        - waitTime
        - unitTime
      properties:
        logMsg:
          title: Enter Log Message
          type: string
          description: Provide Message for logging
        waitTime:
          title: Wait time
          type: number
          description: Time to wait before logging the message
        unitTime:
          title: Time unit
          type: string
          enum:
            - milliseconds
            - seconds
            - minutes
          description: Unit of time for the wait duration

  steps:
    - id: log-info
      name: Log the wait time duration
      action: debug:log
      input:
        message: Waiting for ${{parameters.waitTime}} ${{parameters.unitTime}} before logging message
    - id: wait
      name: Wait Step
      action: debug:wait
      input:
        seconds: |
          {{- if eq parameters.unitTime "seconds" }}
            {{ parameters.waitTime }}
          {{- elif eq parameters.unitTime "milliseconds" }}
            {{ div parameters.waitTime 1000 }}
          {{- elif eq parameters.unitTime "minutes"}}
            {{ mul parameters.waitTime 60}}
    - id: log-msg
      name: Log Message
      action: debug:log
      input:
        message: ${{parameters.logMsg}}

