---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Jsonata
  title: Jsonata
  description: Example template to perform a jsonata expression on input data
spec:
  owner: roadie
  type: service

  parameters:
    - title: Input Data Details
      properties:
        inputData:
          title: JSON
          type: string
          description: JSON to merge in
          ui:widget: textarea
          ui:options:
            rows: 10
          ui:placeholder: |
           {"hello":"world"}

  steps:
    - id: jsonata
      name: Parse File
      action: roadiehq:utils:jsonata
      input:
        data: ${{parameters.inputData}}
        expression: '$'
  output:
    text:
      - title: Output from roadiehq:utils:jsonata
        content: ${{ steps.jsonata.output.result }}
