---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Jsonata
  title: Jsonata
  description: Example template to perform a jsonata expression on input data
spec:
  owner: roadie
  type: service

  parameters:
    - title: Input Data Details
      properties:
        inputData:
          title: Input Data to be Transformed 
          type: string
          description: provide input data to be transformed
  steps:
    - id: jsonata
      name: Parse File
      action: roadiehq:utils:jsonata
      input:
        data: ${{parameters.inputData}}
        expression: '$sum(Account.Order.Product.(Price * Quantity))'
  output:
    text:
      - title: Output from roadiehq:utils:jsonata
        content: ${{parameters.inputData}}
