---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: merge-template
  title: Merge Content 
  description: Merge in some content to an existing file.
spec:
  owner: roadie
  type: service

  parameters:
    properties:
      repository:
        title: Repository name
        type: string
        description: The name of the repository
      org:
        title: Repository Organization
        type: string
        description: The Github org that the repository is in
      path:
        title: Path
        type: string
        description: The path to the desired new file
      content:
        title: Content
        type: string
        description: content to merge in
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: 'https://github.com/${{ parameters.org }}/${{ parameters.repository }}'
    - id: merge
      name: Merge JSON
      action: roadiehq:utils:merge
      input:
        path: ${{ parameters.path }}
        content: ${{ parameters.content }}
    - id: parse
      name: Parse contents of the file
      action: roadiehq:utils:fs:parse
      input:
        path: ${{ parameters.path }}
    - id: log-message
      name: Log contents of the file
      action: debug:log
      input:
        message: 'File contents: ${{ steps["parse"].output.content }}'
    - id: log-message
      name: List files in the workspace
      action: debug:log
      input:
        listWorkspace: true
