# Example template from: https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/scaffolder-actions/scaffolder-backend-module-utils/README.md#example-template 
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: delete-file-template-example
  title: Delete a File
  description: Delete a given file.
spec:
  owner: roadie
  type: service

  parameters:
    - title: PR Data
      properties:
        repository:
          title: Repository name
          type: string
          description: The name of the repository
        org:
          title: Repository Organization
          type: string
          description: The Github org that the repository is in
    - title: File Details
      properties:
        path:
          title: Path
          type: string
          description: The path to the file you want to delete
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/${{ parameters.org }}/${{ parameters.repository }}
    - id: delete-file
      name: Delete File
      action: fs:delete
      input:
        files:
          - ${{ parameters.path }}
    - id: log-message
      name: Log PR URL
      action: debug:log
      input:
        listWorkspace: true